/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from "@react-three/drei";
import React from "react";
import * as THREE from "three";

const _: React.FC = props => {
  const { nodes } = useGLTF("/objects/unicorn.glb");
  const unicornColor = new THREE.Color("white");

  return (
    <group {...props} dispose={null} position={[-2.5, 2.5, 0]} scale={0.75}>
      <group scale={0.005}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_0.geometry}
          position={[352.644, -86.884, 0]}
        >
          <meshStandardMaterial color={unicornColor} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_8.geometry}
          position={[386.739, -475.131, 0.08]}
        >
          <meshStandardMaterial color={unicornColor} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_7.geometry}
          position={[0.014, 0, 0.07]}
        >
          <meshStandardMaterial color={unicornColor} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_6.geometry}
          position={[266.213, -933.405, 0.06]}
        >
          <meshStandardMaterial color={unicornColor} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_5.geometry}
          position={[853.568, -656.791, 0.05]}
        >
          <meshStandardMaterial color={unicornColor} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_4.geometry}
          position={[464.66, -621.059, 0.04]}
        >
          <meshStandardMaterial color={unicornColor} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_3.geometry}
          position={[695.219, -409.731, 0.03]}
        >
          <meshStandardMaterial color={unicornColor} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_2.geometry}
          position={[344.443, -121.466, 0.02]}
        >
          <meshStandardMaterial color={unicornColor} />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Shape_1.geometry}
          position={[839.792, -109.585, 0.01]}
        >
          <meshStandardMaterial color={unicornColor} />
        </mesh>
      </group>
    </group>
  );
};

useGLTF.preload("/objects/unicorn.glb");

export default _;
