/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [101.65KB] > /Users/ty/Downloads/iphone/scene-transformed.glb [406.84KB] (-300%)
Author: akshatmittal (https://sketchfab.com/akshatmittal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-14-pro-max-95f11f5a06604c8b9fd44046ae52a9cc
Title: iPhone 14 Pro Max
*/
import { Html, useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { Material, Mesh } from "three";

// Define the structure for the GLTF nodes
type GLTFResult = {
  nodes: {
    [key: string]: Mesh;
  };
  materials: {
    [key: string]: Material;
  };
};

// Update the props interface to accept a url
interface ModelProps extends GroupProps {
  url: string;
}

export default function Model({ url, ...props }: ModelProps) {
  const gltf = useGLTF("/model/iphone-14-pro.glb");
  const nodes = gltf.nodes as GLTFResult["nodes"];
  const materials = gltf.materials as GLTFResult["materials"];

  return (
    <group {...props} dispose={null} scale={0.25} castShadow>
      <mesh geometry={nodes.UCttAeyROPsgmix.geometry} material={materials.KtvhjlxyToKjYkE} />
      <mesh geometry={nodes.XbtrdVaOWYmkEiU.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.YbXWdqEcjbfTKuN_0.geometry} position={[0, 0, 0]}>
        <color attach="background" args={[0x000000]} />
        <Html
          center
          className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-full pb-2.5"
          style={{
            height: 631,
            width: 290
          }}
          position={[0, 0.05, -0.39]}
          rotation={[0, Math.PI, 0]}
          transform
          occlude
        >
          <div
            className="pointer-events-none relative h-full w-full overflow-hidden rounded-[40px] bg-black pb-10 pt-10"
            onPointerDown={e => e.stopPropagation()}
          >
            <iframe src={url} className="h-full w-full grayscale" />
          </div>
        </Html>
      </mesh>
      <mesh geometry={nodes.lxsKwuOPNvmzBKg_0.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.alSOKOYgFKIcUtR.geometry} material={materials.sWxYOtHGWTcXRMx} />
      <mesh geometry={nodes.AbxQOpRbGREHXRG.geometry} material={materials.IDdMwJVCyuFpUnA} />
      <mesh geometry={nodes.tWfjYtMZCfucxRt.geometry} material={materials.fdfRsQCrfvPBPfQ} />
      <mesh geometry={nodes.rqSonbcVVSPWFfa_0.geometry} material={materials.jFPFAvCbiqflbQV} />
      <mesh geometry={nodes.OMkeKbwVHRBkBwM.geometry} material={materials.IkWzRHNnDaKQXIi} />
      <mesh geometry={nodes.DLfIUIalXuQjJsL.geometry} material={materials.pBMikDFQfUOsKkr} />
      <mesh geometry={nodes.IuMgFUHIyRWENxG_0.geometry} material={materials.LcWBQfBvCzxThpp} />
      <mesh geometry={nodes.dNDonqESZOxUcei_0.geometry} material={materials.LUbRMhkIhuekQRK} />
      <mesh geometry={nodes.QOfJIBEXOvXfSUh.geometry} material={materials.vsSJQngPxBJTVZb} />
      <mesh geometry={nodes.aYjPeBrpBRopJbp.geometry} material={materials.xHgtbqndQshkTKG} />
      <mesh geometry={nodes.tWBbDznHihIxXam.geometry} material={materials.OStzgRHtVBLWwiD} />
      <mesh geometry={nodes.PLFTnNQeqVAxicS.geometry} material={materials.BLpVAsLWNICZYGG} />
      <mesh geometry={nodes.GWEiavWnRxbogtw_0.geometry} material={materials.FsunUcGyajFpQmW} />
      <mesh geometry={nodes.RFqaqXLpuCDBIGV_0.geometry} material={materials.nJRBoEsOhzMSqCz} />
      {/* USB port */}
      <mesh geometry={nodes.BDLCJBydsNjizog_0.geometry} material={materials.fGwijctGaiRaYJC} />
      {/* Far right speaker hole */}
      <mesh geometry={nodes.zPPSOvNamLQVyvv.geometry} material={materials.qEGySvwsouNnVcn} />
      {/* Silent switch */}
      <mesh geometry={nodes.MoTJNOoMxqdxNvQ.geometry} material={materials.IBtgGxCVyZhjKZM}>
        <meshStandardMaterial metalness={1} roughness={0.1} color="silver" />
      </mesh>
      <mesh geometry={nodes.mZxrNiCtMrMjOMv.geometry} material={materials.WqbAhnIPgrrhfXS} />
      {/* Aluminum rails */}
      <mesh geometry={nodes.lgnGJJmNebyRbHq_0.geometry} material={materials.rNCplyWedyfORFh}>
        <meshStandardMaterial metalness={0.7} roughness={0.1} color="black" />
      </mesh>
    </group>
  );
}

useGLTF.preload("/model/iphone-14-pro.glb");
